# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.6

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/trinitycore/realm/lastdawn/src/trinitycore

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/trinitycore/realm/lastdawn/src/trinitycore

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/trinitycore/realm/lastdawn/src/trinitycore/CMakeFiles /home/trinitycore/realm/lastdawn/src/trinitycore/CMakeFiles/progress.make
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/trinitycore/realm/lastdawn/src/trinitycore/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named genrev

# Build rule for target.
genrev: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 genrev
.PHONY : genrev

# fast build rule for target.
genrev/fast:
	$(MAKE) -f CMakeFiles/genrev.dir/build.make CMakeFiles/genrev.dir/build
.PHONY : genrev/fast

#=============================================================================
# Target rules for targets named revision.h

# Build rule for target.
revision.h: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 revision.h
.PHONY : revision.h

# fast build rule for target.
revision.h/fast:
	$(MAKE) -f CMakeFiles/revision.h.dir/build.make CMakeFiles/revision.h.dir/build
.PHONY : revision.h/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named g3dlite

# Build rule for target.
g3dlite: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 g3dlite
.PHONY : g3dlite

# fast build rule for target.
g3dlite/fast:
	$(MAKE) -f dep/src/g3dlite/CMakeFiles/g3dlite.dir/build.make dep/src/g3dlite/CMakeFiles/g3dlite.dir/build
.PHONY : g3dlite/fast

#=============================================================================
# Target rules for targets named trinitysockets

# Build rule for target.
trinitysockets: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 trinitysockets
.PHONY : trinitysockets

# fast build rule for target.
trinitysockets/fast:
	$(MAKE) -f dep/src/sockets/CMakeFiles/trinitysockets.dir/build.make dep/src/sockets/CMakeFiles/trinitysockets.dir/build
.PHONY : trinitysockets/fast

#=============================================================================
# Target rules for targets named zlib

# Build rule for target.
zlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zlib
.PHONY : zlib

# fast build rule for target.
zlib/fast:
	$(MAKE) -f dep/src/zlib/CMakeFiles/zlib.dir/build.make dep/src/zlib/CMakeFiles/zlib.dir/build
.PHONY : zlib/fast

#=============================================================================
# Target rules for targets named ZThread

# Build rule for target.
ZThread: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ZThread
.PHONY : ZThread

# fast build rule for target.
ZThread/fast:
	$(MAKE) -f dep/src/zthread/CMakeFiles/ZThread.dir/build.make dep/src/zthread/CMakeFiles/ZThread.dir/build
.PHONY : ZThread/fast

#=============================================================================
# Target rules for targets named trinityframework

# Build rule for target.
trinityframework: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 trinityframework
.PHONY : trinityframework

# fast build rule for target.
trinityframework/fast:
	$(MAKE) -f src/framework/CMakeFiles/trinityframework.dir/build.make src/framework/CMakeFiles/trinityframework.dir/build
.PHONY : trinityframework/fast

#=============================================================================
# Target rules for targets named shared

# Build rule for target.
shared: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 shared
.PHONY : shared

# fast build rule for target.
shared/fast:
	$(MAKE) -f src/shared/CMakeFiles/shared.dir/build.make src/shared/CMakeFiles/shared.dir/build
.PHONY : shared/fast

#=============================================================================
# Target rules for targets named vmaps

# Build rule for target.
vmaps: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vmaps
.PHONY : vmaps

# fast build rule for target.
vmaps/fast:
	$(MAKE) -f src/shared/vmap/CMakeFiles/vmaps.dir/build.make src/shared/vmap/CMakeFiles/vmaps.dir/build
.PHONY : vmaps/fast

#=============================================================================
# Target rules for targets named trinityauth

# Build rule for target.
trinityauth: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 trinityauth
.PHONY : trinityauth

# fast build rule for target.
trinityauth/fast:
	$(MAKE) -f src/shared/Auth/CMakeFiles/trinityauth.dir/build.make src/shared/Auth/CMakeFiles/trinityauth.dir/build
.PHONY : trinityauth/fast

#=============================================================================
# Target rules for targets named trinityconfig

# Build rule for target.
trinityconfig: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 trinityconfig
.PHONY : trinityconfig

# fast build rule for target.
trinityconfig/fast:
	$(MAKE) -f src/shared/Config/CMakeFiles/trinityconfig.dir/build.make src/shared/Config/CMakeFiles/trinityconfig.dir/build
.PHONY : trinityconfig/fast

#=============================================================================
# Target rules for targets named trinitydatabase

# Build rule for target.
trinitydatabase: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 trinitydatabase
.PHONY : trinitydatabase

# fast build rule for target.
trinitydatabase/fast:
	$(MAKE) -f src/shared/Database/CMakeFiles/trinitydatabase.dir/build.make src/shared/Database/CMakeFiles/trinitydatabase.dir/build
.PHONY : trinitydatabase/fast

#=============================================================================
# Target rules for targets named trinity-realm

# Build rule for target.
trinity-realm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 trinity-realm
.PHONY : trinity-realm

# fast build rule for target.
trinity-realm/fast:
	$(MAKE) -f src/trinityrealm/CMakeFiles/trinity-realm.dir/build.make src/trinityrealm/CMakeFiles/trinity-realm.dir/build
.PHONY : trinity-realm/fast

#=============================================================================
# Target rules for targets named game

# Build rule for target.
game: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 game
.PHONY : game

# fast build rule for target.
game/fast:
	$(MAKE) -f src/game/CMakeFiles/game.dir/build.make src/game/CMakeFiles/game.dir/build
.PHONY : game/fast

#=============================================================================
# Target rules for targets named trinityscript

# Build rule for target.
trinityscript: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 trinityscript
.PHONY : trinityscript

# fast build rule for target.
trinityscript/fast:
	$(MAKE) -f src/bindings/scripts/CMakeFiles/trinityscript.dir/build.make src/bindings/scripts/CMakeFiles/trinityscript.dir/build
.PHONY : trinityscript/fast

#=============================================================================
# Target rules for targets named trinity-core

# Build rule for target.
trinity-core: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 trinity-core
.PHONY : trinity-core

# fast build rule for target.
trinity-core/fast:
	$(MAKE) -f src/trinitycore/CMakeFiles/trinity-core.dir/build.make src/trinitycore/CMakeFiles/trinity-core.dir/build
.PHONY : trinity-core/fast

src/tools/genrevision/genrevision.o: src/tools/genrevision/genrevision.cpp.o
.PHONY : src/tools/genrevision/genrevision.o

# target to build an object file
src/tools/genrevision/genrevision.cpp.o:
	$(MAKE) -f CMakeFiles/genrev.dir/build.make CMakeFiles/genrev.dir/src/tools/genrevision/genrevision.cpp.o
.PHONY : src/tools/genrevision/genrevision.cpp.o

src/tools/genrevision/genrevision.i: src/tools/genrevision/genrevision.cpp.i
.PHONY : src/tools/genrevision/genrevision.i

# target to preprocess a source file
src/tools/genrevision/genrevision.cpp.i:
	$(MAKE) -f CMakeFiles/genrev.dir/build.make CMakeFiles/genrev.dir/src/tools/genrevision/genrevision.cpp.i
.PHONY : src/tools/genrevision/genrevision.cpp.i

src/tools/genrevision/genrevision.s: src/tools/genrevision/genrevision.cpp.s
.PHONY : src/tools/genrevision/genrevision.s

# target to generate assembly for a file
src/tools/genrevision/genrevision.cpp.s:
	$(MAKE) -f CMakeFiles/genrev.dir/build.make CMakeFiles/genrev.dir/src/tools/genrevision/genrevision.cpp.s
.PHONY : src/tools/genrevision/genrevision.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... genrev"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... revision.h"
	@echo "... uninstall"
	@echo "... src/tools/genrevision/genrevision.o"
	@echo "... src/tools/genrevision/genrevision.i"
	@echo "... src/tools/genrevision/genrevision.s"
	@echo "... src/tools/genrevision/genrevision.o"
	@echo "... src/tools/genrevision/genrevision.i"
	@echo "... src/tools/genrevision/genrevision.s"
	@echo "... src/tools/genrevision/genrevision.o"
	@echo "... src/tools/genrevision/genrevision.i"
	@echo "... src/tools/genrevision/genrevision.s"
	@echo "... src/tools/genrevision/genrevision.o"
	@echo "... src/tools/genrevision/genrevision.i"
	@echo "... src/tools/genrevision/genrevision.s"
	@echo "... src/tools/genrevision/genrevision.o"
	@echo "... src/tools/genrevision/genrevision.i"
	@echo "... src/tools/genrevision/genrevision.s"
	@echo "... g3dlite"
	@echo "... src/tools/genrevision/genrevision.o"
	@echo "... src/tools/genrevision/genrevision.i"
	@echo "... src/tools/genrevision/genrevision.s"
	@echo "... trinitysockets"
	@echo "... src/tools/genrevision/genrevision.o"
	@echo "... src/tools/genrevision/genrevision.i"
	@echo "... src/tools/genrevision/genrevision.s"
	@echo "... zlib"
	@echo "... src/tools/genrevision/genrevision.o"
	@echo "... src/tools/genrevision/genrevision.i"
	@echo "... src/tools/genrevision/genrevision.s"
	@echo "... ZThread"
	@echo "... src/tools/genrevision/genrevision.o"
	@echo "... src/tools/genrevision/genrevision.i"
	@echo "... src/tools/genrevision/genrevision.s"
	@echo "... src/tools/genrevision/genrevision.o"
	@echo "... src/tools/genrevision/genrevision.i"
	@echo "... src/tools/genrevision/genrevision.s"
	@echo "... src/tools/genrevision/genrevision.o"
	@echo "... src/tools/genrevision/genrevision.i"
	@echo "... src/tools/genrevision/genrevision.s"
	@echo "... trinityframework"
	@echo "... src/tools/genrevision/genrevision.o"
	@echo "... src/tools/genrevision/genrevision.i"
	@echo "... src/tools/genrevision/genrevision.s"
	@echo "... shared"
	@echo "... src/tools/genrevision/genrevision.o"
	@echo "... src/tools/genrevision/genrevision.i"
	@echo "... src/tools/genrevision/genrevision.s"
	@echo "... vmaps"
	@echo "... src/tools/genrevision/genrevision.o"
	@echo "... src/tools/genrevision/genrevision.i"
	@echo "... src/tools/genrevision/genrevision.s"
	@echo "... trinityauth"
	@echo "... src/tools/genrevision/genrevision.o"
	@echo "... src/tools/genrevision/genrevision.i"
	@echo "... src/tools/genrevision/genrevision.s"
	@echo "... trinityconfig"
	@echo "... src/tools/genrevision/genrevision.o"
	@echo "... src/tools/genrevision/genrevision.i"
	@echo "... src/tools/genrevision/genrevision.s"
	@echo "... trinitydatabase"
	@echo "... src/tools/genrevision/genrevision.o"
	@echo "... src/tools/genrevision/genrevision.i"
	@echo "... src/tools/genrevision/genrevision.s"
	@echo "... trinity-realm"
	@echo "... src/tools/genrevision/genrevision.o"
	@echo "... src/tools/genrevision/genrevision.i"
	@echo "... src/tools/genrevision/genrevision.s"
	@echo "... game"
	@echo "... src/tools/genrevision/genrevision.o"
	@echo "... src/tools/genrevision/genrevision.i"
	@echo "... src/tools/genrevision/genrevision.s"
	@echo "... src/tools/genrevision/genrevision.o"
	@echo "... src/tools/genrevision/genrevision.i"
	@echo "... src/tools/genrevision/genrevision.s"
	@echo "... trinityscript"
	@echo "... src/tools/genrevision/genrevision.o"
	@echo "... src/tools/genrevision/genrevision.i"
	@echo "... src/tools/genrevision/genrevision.s"
	@echo "... trinity-core"
	@echo "... src/tools/genrevision/genrevision.o"
	@echo "... src/tools/genrevision/genrevision.i"
	@echo "... src/tools/genrevision/genrevision.s"
	@echo "... src/tools/genrevision/genrevision.o"
	@echo "... src/tools/genrevision/genrevision.i"
	@echo "... src/tools/genrevision/genrevision.s"
	@echo "... src/tools/genrevision/genrevision.o"
	@echo "... src/tools/genrevision/genrevision.i"
	@echo "... src/tools/genrevision/genrevision.s"
	@echo "... src/tools/genrevision/genrevision.o"
	@echo "... src/tools/genrevision/genrevision.i"
	@echo "... src/tools/genrevision/genrevision.s"
	@echo "... src/tools/genrevision/genrevision.o"
	@echo "... src/tools/genrevision/genrevision.i"
	@echo "... src/tools/genrevision/genrevision.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

