# Install script for directory: /home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates

# Set the install prefix
IF(NOT DEFINED CMAKE_INSTALL_PREFIX)
  SET(CMAKE_INSTALL_PREFIX "/home/trinitycore/realm/lastdawn/release")
ENDIF(NOT DEFINED CMAKE_INSTALL_PREFIX)
STRING(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
IF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  IF(BUILD_TYPE)
    STRING(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  ELSE(BUILD_TYPE)
    SET(CMAKE_INSTALL_CONFIG_NAME "")
  ENDIF(BUILD_TYPE)
  MESSAGE(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
ENDIF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)

# Set the component getting installed.
IF(NOT CMAKE_INSTALL_COMPONENT)
  IF(COMPONENT)
    MESSAGE(STATUS "Install component: \"${COMPONENT}\"")
    SET(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  ELSE(COMPONENT)
    SET(CMAKE_INSTALL_COMPONENT)
  ENDIF(COMPONENT)
ENDIF(NOT CMAKE_INSTALL_COMPONENT)

# Install shared libraries without execute permission?
IF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  SET(CMAKE_INSTALL_SO_NO_EXE "1")
ENDIF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" MATCHES "^(Unspecified)$")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/trinity/sql/updates" TYPE FILE FILES
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1138_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1712_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/220_characters.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1366_characters.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1761_spell_linked_spell.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1820_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/852_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/551_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1437_TC1_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/841_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/741_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/133_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/917_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/TC1_1569_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/238_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1018_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1340_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1616_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/147_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/262_characters.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/230_world_serpent_shrine.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1265_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1765_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/262_realmd.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/537_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1304_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/571_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/175_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/807_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/608_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/66_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/11_characters.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/588_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/332_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/947_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/572_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/724_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/54_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/TC1_1465_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/930_characters.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1311_characters.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/955_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1747_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/541_characters.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/722_world_script_texts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/356_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/TC1_1509_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1607_characters.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1745_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/764_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/783_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1589_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/241_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1792_world_spell_linked_spell.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/82_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1371.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/817_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/725_characters.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1358_characters.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/262_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/950_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/176_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/505_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/965_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/834_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/212_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/871_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/963_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/708_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/70_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/640_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/519_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1605_characters.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/683_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1142_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/513_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1556_characters_ahbot.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/615_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/333_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1730_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1234_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/957_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1726_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/966_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1247_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/692_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/762_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/287_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/123_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/765_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/86_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/951_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1679_characters.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/728_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/833_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/954_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/78_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1638_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/575_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1160_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/822_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/334_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/691_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/927_characters.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/79_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/863_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1632_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/953_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/542_characters.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/826_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/839_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/273_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/952_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/112_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/471_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/541_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/240_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1774_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/231_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1484_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/645_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1073_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/741_characters.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/230_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/TC1_1534_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/latest.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/837_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/502_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/79_characters.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/842_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/230_world_blacktemple.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1687_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/146_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/884_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/970_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/480_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/84_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/838_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/758_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1159_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1318_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/667_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/90_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/676_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/747_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/68_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1164_characters.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/140_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/TC1_1463_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/400_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/230_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/153_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/TC1_1486_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/233_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/389_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/935_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/171_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/919_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/116_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/285_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/410_characters.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/427_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/341_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/182_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1350_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/773_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1637_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1236_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/973_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1249_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/102_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/679_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1074_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/940_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/117_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/45_characters.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1026_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/506_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/TC1_1477_world_spell.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1588_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1366_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/905_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/444_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/785_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1211_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/733_characters.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/152_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/583_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/933_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/57_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/488_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/455_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/83_realmd.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1028_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/247_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/377_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/120_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/725_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1362_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/739_characters.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/948_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/789_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/857_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/840_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/452_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/426_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/125_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1069_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/780_characters.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1261_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1738_TC1_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/329_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/145_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/748_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1358_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/945_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/373_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1421_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/1749_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/686_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/636_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/586_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/172_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/566_world.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/956_world_scripts.sql"
    "/home/trinitycore/realm/lastdawn/src/trinitycore/sql/updates/850_world_scripts.sql"
    )
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" MATCHES "^(Unspecified)$")

